name = "sdk-demo-unity-fe"
main = "src/worker.js"
compatibility_date = "2025-08-20"
workers_dev = true

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "unity-web"

[observability]
enabled = true
head_sampling_rate = 1
